name: module
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  analyzer: ^6.8.0
  analyzer_plugin: any
  collection: ^1.19.1
  path: ^1.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
