name: module
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  analyzer_plugin:
    path: pkg/analyzer_plugin-0.11.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
