name: plugin_loader
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  module:
    git: https://github.com/Ahmed-Omar-Hommir/module